// This file is auto-generated by vscode-router-generator
// Do not edit this file directly

// Page Routes
// "/test": root-module > test-module
// "/settings/admin": root-module > settings-module > admin-settings
// "/settings/": root-module > settings-module > settings-default
// "/settings": root-module > settings-module
// "/dashboard/overview": root-module > dashboard-module > overview-module
// "/dashboard/account/:userid": root-module > dashboard-module > account-module > account-details
// "/dashboard/account/": root-module > dashboard-module > account-module > account-info
// "/dashboard/account": root-module > dashboard-module > account-module
// "/dashboard/": root-module > dashboard-module > dashboard-default
// "/dashboard": root-module > dashboard-module
// "/custom": root-module > custom-route
// "/404": root-module > unknown-route
// "/": root-module > app-module
// "": root-module

import { customElement } from "lit/decorators.js";
import { html, LitElement, TemplateResult } from "lit";
import { renderRoute } from "./router";

@customElement("generated-app")
export class GeneratedApp extends LitElement {
  template: TemplateResult | null = null;

  override render() {
    if (!this.template) return html`Loading...`;
    return this.template;
  }

  override async firstUpdated() {
    window.addEventListener("hashchange", () => this.updateRoute());
    this.updateRoute();
    if (window.location.hash === "") window.location.hash = "/";
  }

  async updateRoute() {
    const route = window.location.hash.slice(1);
    this.template = await renderRoute(route);
    this.requestUpdate();
  }
}
